name: Build

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    permissions: write-all
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            submodules: 'recursive'

      - name: Set target dir
        run: |
          $DriveLetter = $(Get-Location).Drive.Name
          # important. this allows us to get shorter path names
          echo "CARGO_TARGET_DIR=${DriveLetter}:\target" >> $env:GITHUB_ENV

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ github.event_name == 'release' && 'prod' || 'dev' }}
          cache-directories: "${{env.CARGO_TARGET_DIR}}"

      - name: Build
        env:
          RELEASE: ${{ github.event_name == 'release' && '--release' || '' }}
        run: cargo build $env:RELEASE

      - name: Upload Artifacts
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            ${{env.CARGO_TARGET_DIR}}/*/*.dll

      - name: Zip files up
        if: github.event_name == 'release'
        run: |
          Get-ChildItem -Path $env:CARGO_TARGET_DIR/*/*.dll | Compress-Archive -CompressionLevel Optimal -DestinationPath "my-plugin-x64.zip"

      - name: Attach assets to release
        if: github.event_name == 'release'
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "*.zip"
          draft: false
          release_id: ${{ github.event.release.id }}
